### PR TITLE
updating runtime packages

### PR DESCRIPTION
**Pull request by maaly77**
Hi I have added 2 pip packages that I will need for my submission. Can you please update the packages? Thanks

### CODE REVIEW

**Comment by chrisjkuch** [comment]
Please explicitly pin the versions for these libraries. 

Given the amount of time remaining in the competition, it is possible we will not be able to merge before the submission deadline closes. It may be easier and faster for you to simply include these libraries as part of your submission zip.

**Comment by maaly77** [comment]
Hi,

I tried to add the libraries in requirements.txt and pip install it within main.py but it didn’t work

***@***.***



Dr. Vet. Med. Maaly Nassar
Senior Data Scientist
[signature_2778868280]
SciBite Limited BioData Innovation Centre, Wellcome Genome Campus, Hinxton, Cambridge, CB10 1DR


From: Chris Kucharczyk ***@***.***>
Date: Sunday, 3 March 2024 at 06:11
To: drivendataorg/snomed-ct-entity-linking-runtime ***@***.***>
Cc: Nassar, Maaly (ELS-CBH) ***@***.***>, Author ***@***.***>
Subject: Re: [drivendataorg/snomed-ct-entity-linking-runtime] updating runtime packages (PR #14)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Please explicitly pin the versions for these libraries.

Given the amount of time remaining in the competition, it is possible we will not be able to merge before the submission deadline closes. It may be easier and faster for you to simply include these libraries as part of your submission zip.

**Comment by maaly77** [comment]
Hi, I tried to dowload the packages in a "packages" folder inside assets and  pip install it locally but got failed smoked tests. Here are the log of one of the failed smoked tests:
[smoke_test_log.txt](https://github.com/drivendataorg/snomed-ct-entity-linking-runtime/files/14474523/smoke_test_log.txt)

**Comment by chrisjkuch** [comment]
@maaly77 I closed this request as part of #15 (it took a little bit more digging to find versions of chromadb and sacremoses that had compatible sub-dependencies with previously installed packages).

**Pull request closed without merging**
